# Generated by Django 4.2.8 on 2024-01-23 07:59

from django.db import migrations, models
import mainMessages.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainMessages', '0003_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=mainMessages.models.upload_path),
        ),
    ]
